// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dwcjroqiazgwtkvcemve.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR3Y2pyb3FpYXpnd3RrdmNlbXZlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU0NzUxNDQsImV4cCI6MjA1MTA1MTE0NH0.M6TwE2rHnsTEyLgnFwLrA7Fu1Wj0ZPJCrfAc4xyH2xo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);