// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bkhigflzwldjiokbbbjy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJraGlnZmx6d2xkamlva2JiYmp5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQyNTk1MDksImV4cCI6MjA0OTgzNTUwOX0.31AMKPC_2VcIPB3Xu4JQmvGJkNTu0-zM3WQoU_Y5ogA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);